### ISSUE TITLE
Errors when using with ts-node

### ISSUE THREAD

**Issue by msis** [marcomontalbano/figma-export#116]
I'm getting the following `SyntaxError` when following the README for TS:
```
> ts-node ./node_modules/.bin/figma-export use-config .figmaexportrc.ts

REDACTED/node_modules/.bin/figma-export:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at main (REDACTED/node_modules/.pnpm/ts-node@10.4.0_06de4b00c69b73d094e2c5b522a6ad57/node_modules/ts-node/src/bin.ts:331:12)
    at Object.<anonymous> (REDACTED/node_modules/.pnpm/ts-node@10.4.0_06de4b00c69b73d094e2c5b522a6ad57/node_modules/ts-node/src/bin.ts:482:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
 ELIFECYCLE  Command failed with exit code 1.
```

The versions I'm using are:
```
ts-node: v10.4.0
node: v16.13.2
```

`ts-node node_modules/.bin/figma-export --version` gives the same error.

I've tried to match this project's `tsconfig.json` it didn't work.
I'm having `tsconfig.json` with `module: esnext` and `target: esnext` now, but in vain.

**Comment by msis** [comment]
So I think I found the source of the issue, `./node_modules/.bin/figma-export` contains:
```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="$REDACTED/node_modules/.pnpm/@figma-export+cli@4.2.0/node_modules/@figma-export/cli/bin/node_modules:$REDACTED/node_modules/.pnpm/@figma-export+cli@4.2.0/node_modules/@figma-export/cli/node_modules:$REDACTED/node_modules/.pnpm/@figma-export+cli@4.2.0/node_modules/@figma-export/node_modules:$REDACTED/node_modules/.pnpm/@figma-export+cli@4.2.0/node_modules:$REDACTED/node_modules/.pnpm/node_modules:$REDACTED/node_modules:$REDACTED/node_modules:$REDACTED/node_modules:$REDACTED/node_modules:/Users/node_modules:/node_modules:$REDACTED/packages/$REDACTED/node_modules:$REDACTED/packages/node_modules"
else
  export NODE_PATH="$NODE_PATH:$REDACTED/node_modules/.pnpm/@figma-export+cli@4.2.0/node_modules/@figma-export/cli/bin/node_modules:$REDACTED/node_modules/.pnpm/@figma-export+cli@4.2.0/node_modules/@figma-export/cli/node_modules:$REDACTED/node_modules/.pnpm/@figma-export+cli@4.2.0/node_modules/@figma-export/node_modules:$REDACTED/node_modules/.pnpm/@figma-export+cli@4.2.0/node_modules:$REDACTED/node_modules/.pnpm/node_modules:$REDACTED/node_modules:$REDACTED/node_modules:$REDACTED/node_modules:$REDACTED/node_modules:/Users/node_modules:/node_modules:$REDACTED/packages/$REDACTED/node_modules:$REDACTED/packages/node_modules"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../node_modules/.pnpm/@figma-export+cli@4.2.0/node_modules/@figma-export/cli/bin/run" "$@"
else
  exec node  "$basedir/../../../../node_modules/.pnpm/@figma-export+cli@4.2.0/node_modules/@figma-export/cli/bin/run" "$@"
fi
```

Where I think it should be something like (pointing to `@figma-export/cli/bin/run`):
```node
#!/usr/bin/env node

require('../dist/run');
```

So all works when the script is:
```package.json
    "figma:export": "ts-node ./node_modules/@figma-export/cli/bin/run use-config .figmaexportrc.ts",
```

**Comment by marcomontalbano** [comment]
Hi @msis, I just did a try with nodejs 16.13.2, and everything is working properly. I'm using `npm`. Looking to your `./node_modules/.bin/figma-export` file it looks a bit different from what I expected. This is mine: 

```sh
#!/usr/bin/env node

require('../dist/run');
```

Are you using `pnpm`?
Can you share me more information about your setup? Also information about operating system could help me!

Thanks a lot!

**Comment by marcomontalbano** [comment]
I'm back :smile:
I did a try with `pnpm` and it manages the `.bin` folder differently from `yarn` and `npm`.
As you said, doing this `ts-node ./node_modules/@figma-export/cli/bin/run use-config .figmaexportrc.ts` solves the issue. I'll update the reference in the README accordingly!

Thanks to spot this out!
