### ISSUE TITLE
SVGO Transformer Error: Plugin name should be specified

### ISSUE THREAD

**Issue by bacon-delight** [marcomontalbano/figma-export#139]
I'm getting a "Plugin name should be specified" error when using the SVGO transformer. Can anyone please help?

### Snippet
```
require("dotenv").config();

module.exports = {
	commands: [
		[
			"components",
			{
				fileId: process.env.FILE_ID,
				onlyFromPages: ["solid"],
				transformers: [
					require("@figma-export/transform-svg-with-svgo")({
						plugins: [
							{ removeViewBox: false },
							{ removeDimensions: true },
						],
					}),
				],
				outputters: [
					// https://www.npmjs.com/package/@figma-export/output-components-as-es6
					require("@figma-export/output-components-as-svg")({
						output: "./",
					}),
				],
			},
		],
	],
};
```

### Error
```
✖ preparing components
Error: Plugin name should be specified
    at resolvePluginConfig (/Users/bacon/Documents/Projects/Ecosphere Icons/node_modules/svgo/lib/svgo/config.js:113:13)
    at Array.map (<anonymous>)
    at optimize (/Users/bacon/Documents/Projects/Ecosphere Icons/node_modules/svgo/lib/svgo.js:50:37)
    at optimize (/Users/bacon/Documents/Projects/Ecosphere Icons/node_modules/svgo/lib/svgo-node.js:97:10)
    at /Users/bacon/Documents/Projects/Ecosphere Icons/node_modules/@figma-export/transform-svg-with-svgo/dist/index.js:14:44
    at Generator.next (<anonymous>)
    at /Users/bacon/Documents/Projects/Ecosphere Icons/node_modules/@figma-export/transform-svg-with-svgo/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/bacon/Documents/Projects/Ecosphere Icons/node_modules/@figma-export/transform-svg-with-svgo/dist/index.js:4:12)
    at /Users/bacon/Documents/Projects/Ecosphere Icons/node_modules/@figma-export/transform-svg-with-svgo/dist/index.js:13:21
```

**Comment by bacon-delight** [comment]
Recommended change in documentation as per SVGO. Here's the discussion: https://github.com/marcomontalbano/figma-export/discussions/138

**Comment by marcomontalbano** [comment]
Hi @bacon-delight ,
thanks a lot for your investigation.
I forgot to update the README.md when I updated SVGO to latest v2.8.0.
Inside the project root you can find examples like `.figmaexportrc.example.js`. All of these are already up-to-date.

I'll update the README.md accordingly!
